-- MagicPodcast deterministic schema-24 (N-1) migration fixture.
-- Schema source: commit d3e5b81bf193cd1448fe83ed193576f66a5a206a,
-- generated by that revision's canonical versioned migration registry.
-- Data is synthetic and sanitized: no production content, credentials,
-- absolute paths, or external URLs.
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE schema_migrations (
            version INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            applied_at DATETIME NOT NULL
        );
INSERT INTO schema_migrations VALUES(1,'baseline-current-model','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(2,'feed-access-observability','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(3,'feed-snapshot-retrieved-at','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(4,'feed-circuit-state','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(5,'feed-source-verification','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(6,'scheduler-run-history','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(7,'feed-snapshots-last-good','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(8,'podcast-alternative-feeds','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(9,'job-feed-attempts','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(10,'job-compensation-links','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(11,'job-execution-failure-phase','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(12,'single-active-workflow-job','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(13,'feed-user-agent-gates','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(14,'feed-user-agent-recovery','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(15,'episode-triage-decisions','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(16,'homepage-workflow-reports','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(17,'episode-consumption-state','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(18,'consumption-queue-order','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(19,'episode-completion-facts','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(20,'episode-processing-foundation','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(21,'managed-episode-audio-assets','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(22,'focus-processing-schedule-history','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(23,'episode-video-availability','2026-08-30 00:00:00+00:00');
INSERT INTO schema_migrations VALUES(24,'episode-video-availability-check','2026-08-30 00:00:00+00:00');
CREATE TABLE `tags` (`id` integer PRIMARY KEY AUTOINCREMENT,`name` text NOT NULL,`color` text,`created_at` datetime,`updated_at` datetime);
INSERT INTO tags VALUES(1,'fixture-topic','#336699','2026-08-30 00:00:00+00:00','2026-08-30 00:00:00+00:00');
INSERT INTO tags VALUES(2,'fixture-signal','#663399','2026-08-30 00:00:00+00:00','2026-08-30 00:00:00+00:00');
CREATE TABLE `podcasts` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`xyz_id` text,`title` text NOT NULL,`feed_url` text,`i_tunes_id` text,`podcast_guid` text,`description` text,`author` text,`cover_url` text,`link` text,`newest_enclosure_url` text,`newest_enclosure_duration` integer,`last_update` datetime,`oldest_episode_date` datetime,`popularity_score` integer DEFAULT 0,`priority` integer DEFAULT 5,`update_frequency` integer DEFAULT 0,`added_date` datetime,`episode_count` integer DEFAULT 0,`newest_episode_date` datetime,`is_subscribed` numeric DEFAULT true,`is_dead` numeric DEFAULT false,`my_rate` integer DEFAULT 0,`notes` text,`custom_cover_url` text,`feed_url_valid` numeric DEFAULT true,`last_fetched_at` datetime,`fetch_error_count` integer DEFAULT 0,`data_source` text DEFAULT "rss");
INSERT INTO podcasts VALUES(1,'2026-08-30 00:00:00+00:00','2026-08-30 00:00:00+00:00',NULL,'fixture-podcast','Fixture Podcast','fixture-feed',NULL,NULL,'Sanitized fixture description','Fixture Author',NULL,NULL,NULL,NULL,NULL,NULL,0,5,0,NULL,0,NULL,1,0,5,'Sanitized fixture note',NULL,1,NULL,0,'fixture');
CREATE TABLE `episodes` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`podcast_id` integer NOT NULL,`episode_no` text,`title` text NOT NULL,`medium_url` text,`show_notes` text,`published_date` datetime,`duration` integer DEFAULT 0,`link` text,`content` text,`image_url` text,`enclosure_type` text,`enclosure_length` integer DEFAULT 0,`updated_date` datetime,`guid` text,`fetched_at` datetime,`my_rate` integer DEFAULT 0,`notes` text,`video_availability` text NOT NULL DEFAULT "",CONSTRAINT `fk_podcasts_episodes` FOREIGN KEY (`podcast_id`) REFERENCES `podcasts`(`id`) ON DELETE CASCADE,CONSTRAINT `chk_episodes_video_availability` CHECK (video_availability IN ('','unknown','unavailable','available')));
INSERT INTO episodes VALUES(1,'2026-08-30 00:01:00+00:00','2026-08-30 00:01:00+00:00',NULL,1,'1','Fixture Episode 01',NULL,NULL,'2026-08-01 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-01',NULL,5,'fixture-note-01','');
INSERT INTO episodes VALUES(2,'2026-08-30 00:02:00+00:00','2026-08-30 00:02:00+00:00',NULL,1,'2','Fixture Episode 02',NULL,NULL,'2026-08-02 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-02',NULL,4,'fixture-note-02','unknown');
INSERT INTO episodes VALUES(3,'2026-08-30 00:03:00+00:00','2026-08-30 00:03:00+00:00',NULL,1,'3','Fixture Episode 03',NULL,NULL,'2026-08-03 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-03',NULL,3,'fixture-note-03','unavailable');
INSERT INTO episodes VALUES(4,'2026-08-30 00:04:00+00:00','2026-08-30 00:04:00+00:00',NULL,1,'4','Fixture Episode 04',NULL,NULL,'2026-08-04 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-04',NULL,2,'fixture-note-04','available');
INSERT INTO episodes VALUES(5,'2026-08-30 00:05:00+00:00','2026-08-30 00:05:00+00:00',NULL,1,'5','Fixture Episode 05',NULL,NULL,'2026-08-05 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-05',NULL,5,'fixture-note-05','');
INSERT INTO episodes VALUES(6,'2026-08-30 00:06:00+00:00','2026-08-30 00:06:00+00:00',NULL,1,'6','Fixture Episode 06',NULL,NULL,'2026-08-06 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-06',NULL,4,'fixture-note-06','');
INSERT INTO episodes VALUES(7,'2026-08-30 00:07:00+00:00','2026-08-30 00:07:00+00:00',NULL,1,'7','Fixture Episode 07',NULL,NULL,'2026-08-07 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-07',NULL,3,'fixture-note-07','');
INSERT INTO episodes VALUES(8,'2026-08-30 00:08:00+00:00','2026-08-30 00:08:00+00:00',NULL,1,'8','Fixture Episode 08',NULL,NULL,'2026-08-08 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-08',NULL,2,'fixture-note-08','');
INSERT INTO episodes VALUES(9,'2026-08-30 00:09:00+00:00','2026-08-30 00:09:00+00:00',NULL,1,'9','Fixture Episode 09',NULL,NULL,'2026-08-09 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-09',NULL,1,'fixture-note-09','');
INSERT INTO episodes VALUES(10,'2026-08-30 00:10:00+00:00','2026-08-30 00:10:00+00:00',NULL,1,'10','Fixture Episode 10',NULL,NULL,'2026-08-10 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-10',NULL,5,'fixture-note-10','');
INSERT INTO episodes VALUES(11,'2026-08-30 00:11:00+00:00','2026-08-30 00:11:00+00:00',NULL,1,'11','Fixture Episode 11',NULL,NULL,'2026-08-11 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-11',NULL,4,'fixture-note-11','');
INSERT INTO episodes VALUES(12,'2026-08-30 00:12:00+00:00','2026-08-30 00:12:00+00:00',NULL,1,'12','Fixture Episode 12',NULL,NULL,'2026-08-12 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-12',NULL,3,'fixture-note-12','');
INSERT INTO episodes VALUES(13,'2026-08-30 00:13:00+00:00','2026-08-30 00:13:00+00:00',NULL,1,'13','Fixture Episode 13',NULL,NULL,'2026-08-13 00:00:00+00:00',0,NULL,NULL,NULL,NULL,0,NULL,'fixture-episode-13',NULL,2,'fixture-note-13','');
CREATE TABLE `episodes_tags` (`episode_id` integer,`tag_id` integer,PRIMARY KEY (`episode_id`,`tag_id`),CONSTRAINT `fk_episodes_tags_episode` FOREIGN KEY (`episode_id`) REFERENCES `episodes`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_episodes_tags_tag` FOREIGN KEY (`tag_id`) REFERENCES `tags`(`id`) ON DELETE CASCADE);
INSERT INTO episodes_tags VALUES(1,1);
INSERT INTO episodes_tags VALUES(5,1);
INSERT INTO episodes_tags VALUES(5,2);
INSERT INTO episodes_tags VALUES(11,2);
CREATE TABLE `podcasts_tags` (`podcast_id` integer,`tag_id` integer,PRIMARY KEY (`podcast_id`,`tag_id`),CONSTRAINT `fk_podcasts_tags_podcast` FOREIGN KEY (`podcast_id`) REFERENCES `podcasts`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_podcasts_tags_tag` FOREIGN KEY (`tag_id`) REFERENCES `tags`(`id`) ON DELETE CASCADE);
INSERT INTO podcasts_tags VALUES(1,1);
INSERT INTO podcasts_tags VALUES(1,2);
CREATE TABLE `workflows` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text NOT NULL,`description` text,`schedule` text NOT NULL,`scope_type` text NOT NULL,`scope_config` json,`rules_config` json,`is_enabled` numeric NOT NULL,`publish_to_homepage` numeric NOT NULL DEFAULT false,`report_type` text NOT NULL DEFAULT "",`last_job_id` integer,`last_execution_at` datetime,`next_run_at` datetime);
CREATE TABLE `sync_configs` (`id` integer PRIMARY KEY AUTOINCREMENT,`config_key` text NOT NULL,`config_value` text NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE TABLE `podcast_alternative_feeds` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`podcast_id` integer NOT NULL,`main_feed_url` text NOT NULL DEFAULT "",`identity_key` text NOT NULL DEFAULT "",`alternative_feed_url` text NOT NULL DEFAULT "",`status` text NOT NULL DEFAULT "",`verification` text NOT NULL DEFAULT "",`unavailable_reason` text NOT NULL DEFAULT "",`verified_at` datetime NOT NULL);
CREATE TABLE `episode_completions` (`episode_id` integer,`completed_at` datetime NOT NULL,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,PRIMARY KEY (`episode_id`),CONSTRAINT `fk_episode_completions_episode` FOREIGN KEY (`episode_id`) REFERENCES `episodes`(`id`) ON DELETE CASCADE);
INSERT INTO episode_completions VALUES(11,'2026-08-30 05:11:00+00:00','2026-08-30 05:11:00+00:00','2026-08-30 05:11:00+00:00');
INSERT INTO episode_completions VALUES(12,'2026-08-30 05:12:00+00:00','2026-08-30 05:12:00+00:00','2026-08-30 05:12:00+00:00');
INSERT INTO episode_completions VALUES(13,'2026-08-30 05:13:00+00:00','2026-08-30 05:13:00+00:00','2026-08-30 05:13:00+00:00');
CREATE TABLE `episode_triage_decisions` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`episode_id` integer NOT NULL,`state` text NOT NULL,`decided_at` datetime NOT NULL,`queue_state` text,`queue_position` integer,`dismissed_at` datetime,`queue_updated_at` datetime,`in_progress_at` datetime,`read_at` datetime,CONSTRAINT `fk_episode_triage_decisions_episode` FOREIGN KEY (`episode_id`) REFERENCES `episodes`(`id`) ON DELETE CASCADE);
INSERT INTO episode_triage_decisions VALUES(1,'2026-08-30 01:01:00+00:00','2026-08-30 01:01:00+00:00',NULL,1,'shortlisted','2026-08-30 01:01:00+00:00','inbox',10,NULL,'2026-08-30 01:01:00+00:00',NULL,NULL);
INSERT INTO episode_triage_decisions VALUES(2,'2026-08-30 01:02:00+00:00','2026-08-30 01:02:00+00:00',NULL,2,'shortlisted','2026-08-30 01:02:00+00:00','inbox',20,NULL,'2026-08-30 01:02:00+00:00',NULL,'2026-08-30 02:02:00+00:00');
INSERT INTO episode_triage_decisions VALUES(3,'2026-08-30 01:03:00+00:00','2026-08-30 01:03:00+00:00',NULL,3,'shortlisted','2026-08-30 01:03:00+00:00','inbox',30,NULL,'2026-08-30 01:03:00+00:00',NULL,NULL);
INSERT INTO episode_triage_decisions VALUES(4,'2026-08-30 01:04:00+00:00','2026-08-30 01:04:00+00:00',NULL,4,'shortlisted','2026-08-30 01:04:00+00:00','inbox',40,NULL,'2026-08-30 01:04:00+00:00',NULL,NULL);
INSERT INTO episode_triage_decisions VALUES(5,'2026-08-30 01:05:00+00:00','2026-08-30 01:05:00+00:00',NULL,5,'shortlisted','2026-08-30 01:05:00+00:00','focus',10,NULL,'2026-08-30 01:05:00+00:00','2026-08-30 02:05:00+00:00','2026-08-30 03:05:00+00:00');
INSERT INTO episode_triage_decisions VALUES(6,'2026-08-30 01:06:00+00:00','2026-08-30 01:06:00+00:00',NULL,6,'shortlisted','2026-08-30 01:06:00+00:00','focus',20,NULL,'2026-08-30 01:06:00+00:00',NULL,NULL);
INSERT INTO episode_triage_decisions VALUES(7,'2026-08-30 01:07:00+00:00','2026-08-30 01:07:00+00:00',NULL,7,'shortlisted','2026-08-30 01:07:00+00:00','focus',30,NULL,'2026-08-30 01:07:00+00:00',NULL,NULL);
INSERT INTO episode_triage_decisions VALUES(8,'2026-08-30 01:08:00+00:00','2026-08-30 01:08:00+00:00',NULL,8,'shortlisted','2026-08-30 01:08:00+00:00','someday',10,NULL,'2026-08-30 01:08:00+00:00',NULL,NULL);
INSERT INTO episode_triage_decisions VALUES(9,'2026-08-30 01:09:00+00:00','2026-08-30 01:09:00+00:00',NULL,9,'shortlisted','2026-08-30 01:09:00+00:00','someday',20,NULL,'2026-08-30 01:09:00+00:00',NULL,NULL);
INSERT INTO episode_triage_decisions VALUES(10,'2026-08-30 01:10:00+00:00','2026-08-30 01:10:00+00:00',NULL,10,'shortlisted','2026-08-30 01:10:00+00:00','someday',30,NULL,'2026-08-30 01:10:00+00:00',NULL,NULL);
INSERT INTO episode_triage_decisions VALUES(11,'2026-08-30 01:11:00+00:00','2026-08-30 01:11:00+00:00',NULL,11,'shortlisted','2026-08-30 01:11:00+00:00','done',10,NULL,'2026-08-30 01:11:00+00:00','2026-08-30 02:11:00+00:00','2026-08-30 03:11:00+00:00');
INSERT INTO episode_triage_decisions VALUES(12,'2026-08-30 01:12:00+00:00','2026-08-30 01:12:00+00:00',NULL,12,'shortlisted','2026-08-30 01:12:00+00:00','done',20,NULL,'2026-08-30 01:12:00+00:00',NULL,'2026-08-30 03:12:00+00:00');
INSERT INTO episode_triage_decisions VALUES(13,'2026-08-30 01:13:00+00:00','2026-08-30 01:13:00+00:00',NULL,13,'shortlisted','2026-08-30 01:13:00+00:00','done',30,NULL,'2026-08-30 01:13:00+00:00',NULL,NULL);
CREATE TABLE `consumption_queue_orders` (`queue_state` text,`revision` integer NOT NULL,`updated_at` datetime NOT NULL,PRIMARY KEY (`queue_state`));
INSERT INTO consumption_queue_orders VALUES('inbox',7,'2026-08-30 04:00:00+00:00');
INSERT INTO consumption_queue_orders VALUES('focus',8,'2026-08-30 04:00:00+00:00');
INSERT INTO consumption_queue_orders VALUES('someday',9,'2026-08-30 04:00:00+00:00');
INSERT INTO consumption_queue_orders VALUES('done',10,'2026-08-30 04:00:00+00:00');
CREATE TABLE `episode_processing_runs` (`id` integer PRIMARY KEY AUTOINCREMENT,`episode_id` integer NOT NULL,`processing_key` text NOT NULL,`audio_digest` text NOT NULL,`pipeline_version` text NOT NULL,`trigger_source` text NOT NULL,`schedule_run_id` integer,`status` text NOT NULL,`current_step` text NOT NULL DEFAULT "",`previous_run_id` integer,`attempt_count` integer NOT NULL DEFAULT 0,`max_attempts` integer NOT NULL DEFAULT 3,`retry_deadline_at` datetime NOT NULL,`next_attempt_at` datetime,`started_at` datetime,`finished_at` datetime,`cancelled_at` datetime,`error_code` text NOT NULL DEFAULT "",`error_message` text NOT NULL DEFAULT "",`error_retryable` numeric NOT NULL DEFAULT false,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,CONSTRAINT `fk_episode_processing_runs_episode` FOREIGN KEY (`episode_id`) REFERENCES `episodes`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_episode_processing_runs_previous_run` FOREIGN KEY (`previous_run_id`) REFERENCES `episode_processing_runs`(`id`) ON DELETE SET NULL,CONSTRAINT `chk_processing_run_status` CHECK (status IN ('queued','running','waiting_external','completed','failed','cancelled')),CONSTRAINT `chk_processing_run_trigger` CHECK (trigger_source IN ('manual','scheduled')));
INSERT INTO episode_processing_runs VALUES(1,5,'1111111111111111111111111111111111111111111111111111111111111111','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','fixture-pipeline-v1','manual',NULL,'completed','publish',NULL,1,3,'2026-08-31 00:00:00+00:00',NULL,NULL,'2026-08-30 06:00:00+00:00',NULL,'','',0,'2026-08-30 05:30:00+00:00','2026-08-30 06:00:00+00:00');
CREATE TABLE `processing_checkpoints` (`id` integer PRIMARY KEY AUTOINCREMENT,`run_id` integer NOT NULL,`step` text NOT NULL,`adapter` text NOT NULL,`adapter_version` text NOT NULL,`status` text NOT NULL,`state_json` text NOT NULL,`state_hash` text NOT NULL,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,CONSTRAINT `fk_processing_checkpoints_run` FOREIGN KEY (`run_id`) REFERENCES `episode_processing_runs`(`id`) ON DELETE CASCADE,CONSTRAINT `chk_processing_checkpoint_status` CHECK (status IN ('waiting','completed')));
INSERT INTO processing_checkpoints VALUES(1,1,'minutes','fixture-adapter','v1','completed','{"fixture":true}','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','2026-08-30 05:40:00+00:00','2026-08-30 05:50:00+00:00');
CREATE TABLE `episode_artifact_sets` (`id` integer PRIMARY KEY AUTOINCREMENT,`run_id` integer NOT NULL,`episode_id` integer NOT NULL,`pipeline_version` text NOT NULL,`root_path` text NOT NULL,`manifest_path` text NOT NULL,`manifest_sha256` text NOT NULL,`transcript_sha256` text NOT NULL,`notes_sha256` text NOT NULL,`is_current` numeric NOT NULL DEFAULT false,`created_at` datetime NOT NULL,CONSTRAINT `fk_episode_artifact_sets_episode` FOREIGN KEY (`episode_id`) REFERENCES `episodes`(`id`) ON DELETE CASCADE,CONSTRAINT `fk_episode_artifact_sets_run` FOREIGN KEY (`run_id`) REFERENCES `episode_processing_runs`(`id`) ON DELETE CASCADE);
INSERT INTO episode_artifact_sets VALUES(1,1,5,'fixture-pipeline-v1','artifacts/fixture-run','manifest.json','cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc','dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd','eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',1,'2026-08-30 06:00:00+00:00');
CREATE TABLE `knowledge_deliveries` (`id` integer PRIMARY KEY AUTOINCREMENT,`artifact_set_id` integer NOT NULL,`target` text NOT NULL,`destination` text NOT NULL,`adapter_version` text NOT NULL,`delivery_key` text NOT NULL,`status` text NOT NULL,`attempt_count` integer NOT NULL DEFAULT 0,`remote_ref` text NOT NULL DEFAULT "",`public_url` text NOT NULL DEFAULT "",`error_code` text NOT NULL DEFAULT "",`error_message` text NOT NULL DEFAULT "",`error_retryable` numeric NOT NULL DEFAULT false,`delivered_at` datetime,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,CONSTRAINT `fk_knowledge_deliveries_artifact_set` FOREIGN KEY (`artifact_set_id`) REFERENCES `episode_artifact_sets`(`id`) ON DELETE CASCADE,CONSTRAINT `chk_knowledge_delivery_status` CHECK (status IN ('pending','delivering','delivered','failed','cancelled')));
INSERT INTO knowledge_deliveries VALUES(1,1,'fixture-kb','fixture-destination','v1','ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff','delivered',1,'fixture-ref','','','',0,'2026-08-30 06:10:00+00:00','2026-08-30 06:05:00+00:00','2026-08-30 06:10:00+00:00');
CREATE TABLE `jobs` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`workflow_id` integer NOT NULL,`status` text NOT NULL,`start_time` datetime,`end_time` datetime,`podcasts_processed` integer DEFAULT 0,`episodes_found` integer DEFAULT 0,`episodes_created` integer DEFAULT 0,`episodes_matched` integer DEFAULT 0,`error_count` integer DEFAULT 0,`triggered_by` text DEFAULT "cron",`compensation_of_job_id` integer,`compensated_by_job_id` integer,CONSTRAINT `fk_workflows_jobs` FOREIGN KEY (`workflow_id`) REFERENCES `workflows`(`id`));
CREATE TABLE `job_executions` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`job_id` integer NOT NULL,`podcast_id` integer,`podcast_title` text,`podcast_feed_url` text,`status` text NOT NULL,`episodes_found` integer DEFAULT 0,`episodes_created` integer DEFAULT 0,`episodes_matched` integer DEFAULT 0,`error_message` text,`log_info` text,`processing_time` integer DEFAULT 0,`feed_http_status` integer,`feed_error_category` text NOT NULL DEFAULT "not_observed",`feed_target_domain` text NOT NULL DEFAULT "",`feed_response_time_ms` integer NOT NULL DEFAULT 0,`feed_retry_after` text NOT NULL DEFAULT "",`feed_etag` text NOT NULL DEFAULT "",`feed_last_modified` text NOT NULL DEFAULT "",`feed_cache_control` text NOT NULL DEFAULT "",`feed_expires` text NOT NULL DEFAULT "",`feed_age` text NOT NULL DEFAULT "",`feed_response_bytes` integer NOT NULL DEFAULT 0,`feed_source_type` text NOT NULL DEFAULT "unknown",`feed_source_url` text NOT NULL DEFAULT "",`feed_identity_verification` text NOT NULL DEFAULT "not_checked",`feed_cache_status` text NOT NULL DEFAULT "not_used",`feed_freshness` text NOT NULL DEFAULT "unknown",`feed_egress_id` text NOT NULL DEFAULT "unknown",`feed_snapshot_retrieved_at` datetime,`feed_circuit_state` text NOT NULL DEFAULT "not_used",`feed_failure_phase` text NOT NULL DEFAULT "",`feed_user_agent_gate_state` text NOT NULL DEFAULT "",`feed_user_agent_probe_result` text NOT NULL DEFAULT "",`feed_user_agent_approved_by` text NOT NULL DEFAULT "",`feed_user_agent_approved_at` datetime,`feed_user_agent_last_probe_at` datetime,CONSTRAINT `fk_jobs_executions` FOREIGN KEY (`job_id`) REFERENCES `jobs`(`id`));
CREATE TABLE `job_feed_attempts` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`job_id` integer NOT NULL,`podcast_id` integer NOT NULL,`attempt_no` integer NOT NULL DEFAULT 1,`source_type` text NOT NULL DEFAULT "primary",`attempted_at` datetime NOT NULL,`http_status` integer,`error_category` text NOT NULL DEFAULT "not_observed",`failure_phase` text NOT NULL DEFAULT "",`retry_decision` text NOT NULL DEFAULT "",`identity_verification` text NOT NULL DEFAULT "not_checked",`target_domain` text NOT NULL DEFAULT "",`source_url` text NOT NULL DEFAULT "",`is_final_result` numeric NOT NULL DEFAULT false,`derived_policy` numeric NOT NULL DEFAULT false,`feed_user_agent_gate_state` text NOT NULL DEFAULT "",`feed_user_agent_probe_result` text NOT NULL DEFAULT "",`feed_user_agent_approved_by` text NOT NULL DEFAULT "",`feed_user_agent_approved_at` datetime,`feed_user_agent_last_probe_at` datetime);
CREATE TABLE `scheduler_runs` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`workflow_id` integer NOT NULL,`status` text NOT NULL,`scheduled_at` datetime NOT NULL,`started_at` datetime,`completed_at` datetime,`duration` integer,`reason` text,`job_id` integer);
CREATE TABLE `reports` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`job_id` integer NOT NULL,`title` text NOT NULL,`content` text NOT NULL,`summary` text,`episodes_count` integer DEFAULT 0,`podcasts_count` integer DEFAULT 0,`matched_count` integer DEFAULT 0,`time_range_start` datetime,`time_range_end` datetime,`time_range_mode` text,`generated_at` datetime NOT NULL,`format` text DEFAULT "markdown",`file_size` integer DEFAULT 0,`publish_to_homepage` numeric NOT NULL DEFAULT false,`report_type` text NOT NULL DEFAULT "",`workflow_name` text NOT NULL DEFAULT "",`structured_episodes` json,`llm_summary` text,`llm_model_used` text,`llm_tokens_used` integer DEFAULT 0,`llm_error` text);
CREATE TABLE feed_snapshots (
    feed_url          TEXT PRIMARY KEY,
    retrieved_at      INTEGER NOT NULL,
    fingerprint       TEXT NOT NULL,
    raw_content       BLOB NOT NULL,
    content_length    INTEGER NOT NULL,
    etag              TEXT NOT NULL DEFAULT '',
    last_modified     TEXT NOT NULL DEFAULT '',
    validated_at      INTEGER NOT NULL,
    source_at_capture TEXT NOT NULL DEFAULT ''
);
CREATE TABLE feed_user_agent_gates (
    domain                   TEXT NOT NULL,
    user_agent_fingerprint   TEXT NOT NULL,
    state                    TEXT NOT NULL DEFAULT 'blocked',
    detected_at              INTEGER NOT NULL,
    probe_eligible_at        INTEGER NOT NULL,
    last_probe_result        TEXT NOT NULL DEFAULT '',
    recovery_success_count   INTEGER NOT NULL DEFAULT 0,
    updated_at               INTEGER NOT NULL, approved_by TEXT NOT NULL DEFAULT '', approved_at INTEGER, last_probe_at INTEGER,
    PRIMARY KEY (domain, user_agent_fingerprint)
);
CREATE TABLE feed_user_agent_gate_audits (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    domain                   TEXT NOT NULL,
    user_agent_fingerprint   TEXT NOT NULL,
    action                   TEXT NOT NULL,
    mode                     TEXT NOT NULL,
    actor                    TEXT NOT NULL DEFAULT '',
    result                   TEXT NOT NULL DEFAULT '',
    created_at               INTEGER NOT NULL
);
CREATE TABLE feed_user_agent_gate_recovery_feeds (
    domain                   TEXT NOT NULL,
    user_agent_fingerprint   TEXT NOT NULL,
    feed_fingerprint         TEXT NOT NULL,
    status                   TEXT NOT NULL DEFAULT 'in_flight',
    first_observed_at        INTEGER NOT NULL,
    last_success_at          INTEGER,
    PRIMARY KEY (domain, user_agent_fingerprint, feed_fingerprint)
);
CREATE TABLE `episode_audio_assets` (`id` integer PRIMARY KEY AUTOINCREMENT,`episode_id` integer NOT NULL,`source_digest` text NOT NULL,`status` text NOT NULL,`relative_path` text NOT NULL DEFAULT "",`sha256` text NOT NULL DEFAULT "",`size_bytes` integer NOT NULL DEFAULT 0,`duration_seconds` integer NOT NULL,`media_type` text NOT NULL DEFAULT "",`extension` text NOT NULL DEFAULT "",`error_code` text NOT NULL DEFAULT "",`error_message` text NOT NULL DEFAULT "",`claim_token` text NOT NULL DEFAULT "",`claim_expires_at` datetime,`queued_at` datetime NOT NULL,`downloading_at` datetime,`ready_at` datetime,`failed_at` datetime,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,CONSTRAINT `fk_episode_audio_assets_episode` FOREIGN KEY (`episode_id`) REFERENCES `episodes`(`id`) ON DELETE CASCADE,CONSTRAINT `chk_episode_audio_asset_status` CHECK (status IN ('queued','downloading','ready','failed')));
INSERT INTO episode_audio_assets VALUES(1,5,'abababababababababababababababababababababababababababababababab','ready','audio/fixture-05.m4a','cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd',1234,321,'audio/mp4','m4a','','','',NULL,'2026-08-30 05:20:00+00:00',NULL,'2026-08-30 05:25:00+00:00',NULL,'2026-08-30 05:20:00+00:00','2026-08-30 05:25:00+00:00');
CREATE TABLE `processing_schedule_runs` (`id` integer PRIMARY KEY AUTOINCREMENT,`trigger_key` text NOT NULL,`scheduled_for` datetime NOT NULL,`cron_expression` text NOT NULL,`timezone` text NOT NULL,`batch_size` integer NOT NULL,`status` text NOT NULL,`candidate_count` integer NOT NULL DEFAULT 0,`started_count` integer NOT NULL DEFAULT 0,`skipped_count` integer NOT NULL DEFAULT 0,`error_code` text NOT NULL DEFAULT "",`error_message` text NOT NULL DEFAULT "",`finished_at` datetime,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,CONSTRAINT `chk_processing_schedule_status` CHECK (status IN ('running','completed','failed')));
INSERT INTO processing_schedule_runs VALUES(1,'fixture-schedule-20260830','2026-08-30 05:00:00+00:00','0 5 * * *','UTC',1,'completed',1,1,0,'','','2026-08-30 05:01:00+00:00','2026-08-30 05:00:00+00:00','2026-08-30 05:01:00+00:00');
CREATE TABLE `processing_schedule_items` (`id` integer PRIMARY KEY AUTOINCREMENT,`schedule_run_id` integer NOT NULL,`episode_id` integer NOT NULL,`queue_position` integer NOT NULL,`outcome` text NOT NULL,`reason` text NOT NULL DEFAULT "",`processing_run_id` integer,`created_at` datetime NOT NULL,`updated_at` datetime NOT NULL,CONSTRAINT `chk_processing_schedule_item_outcome` CHECK (outcome IN ('started','skipped')));
INSERT INTO processing_schedule_items VALUES(1,1,5,10,'started','fixture-selected',1,'2026-08-30 05:00:30+00:00','2026-08-30 05:00:30+00:00');
INSERT INTO sqlite_sequence VALUES('tags',2);
INSERT INTO sqlite_sequence VALUES('podcasts',1);
INSERT INTO sqlite_sequence VALUES('episodes',13);
INSERT INTO sqlite_sequence VALUES('episode_triage_decisions',13);
INSERT INTO sqlite_sequence VALUES('episode_processing_runs',1);
INSERT INTO sqlite_sequence VALUES('processing_checkpoints',1);
INSERT INTO sqlite_sequence VALUES('episode_artifact_sets',1);
INSERT INTO sqlite_sequence VALUES('knowledge_deliveries',1);
INSERT INTO sqlite_sequence VALUES('episode_audio_assets',1);
INSERT INTO sqlite_sequence VALUES('processing_schedule_runs',1);
INSERT INTO sqlite_sequence VALUES('processing_schedule_items',1);
CREATE TRIGGER trg_episode_processing_runs_terminal_status
BEFORE UPDATE OF status ON episode_processing_runs
WHEN OLD.status IN ('completed', 'failed', 'cancelled')
 AND NEW.status <> OLD.status
BEGIN
	SELECT RAISE(ABORT, 'terminal processing run status is immutable');
END;
CREATE UNIQUE INDEX `idx_tags_name` ON `tags`(`name`);
CREATE UNIQUE INDEX `idx_podcasts_feed_url` ON `podcasts`(`feed_url`);
CREATE UNIQUE INDEX `idx_podcasts_xyz_id` ON `podcasts`(`xyz_id`);
CREATE INDEX `idx_podcasts_deleted_at` ON `podcasts`(`deleted_at`);
CREATE UNIQUE INDEX `idx_episodes_guid` ON `episodes`(`guid`);
CREATE INDEX `idx_episodes_podcast_id` ON `episodes`(`podcast_id`);
CREATE INDEX `idx_episodes_deleted_at` ON `episodes`(`deleted_at`);
CREATE INDEX `idx_workflows_last_execution_at` ON `workflows`(`last_execution_at`);
CREATE INDEX `idx_workflows_last_job_id` ON `workflows`(`last_job_id`);
CREATE INDEX `idx_workflows_publish_to_homepage` ON `workflows`(`publish_to_homepage`);
CREATE INDEX `idx_workflows_is_enabled` ON `workflows`(`is_enabled`);
CREATE INDEX `idx_workflows_scope_type` ON `workflows`(`scope_type`);
CREATE INDEX `idx_workflows_deleted_at` ON `workflows`(`deleted_at`);
CREATE INDEX `idx_workflows_next_run_at` ON `workflows`(`next_run_at`);
CREATE UNIQUE INDEX `idx_sync_configs_config_key` ON `sync_configs`(`config_key`);
CREATE UNIQUE INDEX `idx_alt_feed_podcast` ON `podcast_alternative_feeds`(`podcast_id`);
CREATE INDEX `idx_podcast_alternative_feeds_deleted_at` ON `podcast_alternative_feeds`(`deleted_at`);
CREATE INDEX `idx_episode_completions_completed_at` ON `episode_completions`(`completed_at`);
CREATE INDEX `idx_episode_triage_decisions_in_progress_at` ON `episode_triage_decisions`(`in_progress_at`);
CREATE INDEX `idx_episode_triage_decisions_dismissed_at` ON `episode_triage_decisions`(`dismissed_at`);
CREATE INDEX `idx_episode_triage_decisions_queue_state` ON `episode_triage_decisions`(`queue_state`);
CREATE INDEX `idx_episode_triage_decisions_read_at` ON `episode_triage_decisions`(`read_at`);
CREATE INDEX `idx_episode_triage_decisions_queue_updated_at` ON `episode_triage_decisions`(`queue_updated_at`);
CREATE INDEX `idx_episode_triage_decisions_decided_at` ON `episode_triage_decisions`(`decided_at`);
CREATE INDEX `idx_episode_triage_decisions_state` ON `episode_triage_decisions`(`state`);
CREATE UNIQUE INDEX `idx_episode_triage_decisions_episode_id` ON `episode_triage_decisions`(`episode_id`);
CREATE INDEX `idx_episode_triage_decisions_deleted_at` ON `episode_triage_decisions`(`deleted_at`);
CREATE INDEX `idx_episode_processing_runs_previous_run_id` ON `episode_processing_runs`(`previous_run_id`);
CREATE INDEX `idx_episode_processing_runs_status` ON `episode_processing_runs`(`status`);
CREATE INDEX `idx_episode_processing_runs_schedule_run_id` ON `episode_processing_runs`(`schedule_run_id`);
CREATE INDEX `idx_episode_processing_runs_updated_at` ON `episode_processing_runs`(`updated_at`);
CREATE INDEX `idx_episode_processing_runs_finished_at` ON `episode_processing_runs`(`finished_at`);
CREATE INDEX `idx_episode_processing_runs_processing_key` ON `episode_processing_runs`(`processing_key`);
CREATE INDEX `idx_episode_processing_runs_episode_id` ON `episode_processing_runs`(`episode_id`);
CREATE INDEX `idx_episode_processing_runs_created_at` ON `episode_processing_runs`(`created_at`);
CREATE INDEX `idx_episode_processing_runs_next_attempt_at` ON `episode_processing_runs`(`next_attempt_at`);
CREATE UNIQUE INDEX `idx_processing_checkpoint_run_step` ON `processing_checkpoints`(`run_id`,`step`);
CREATE INDEX `idx_episode_artifact_sets_is_current` ON `episode_artifact_sets`(`is_current`);
CREATE INDEX `idx_episode_artifact_sets_episode_id` ON `episode_artifact_sets`(`episode_id`);
CREATE UNIQUE INDEX `idx_episode_artifact_sets_run_id` ON `episode_artifact_sets`(`run_id`);
CREATE INDEX `idx_episode_artifact_sets_created_at` ON `episode_artifact_sets`(`created_at`);
CREATE INDEX `idx_knowledge_deliveries_updated_at` ON `knowledge_deliveries`(`updated_at`);
CREATE INDEX `idx_knowledge_deliveries_created_at` ON `knowledge_deliveries`(`created_at`);
CREATE INDEX `idx_knowledge_deliveries_status` ON `knowledge_deliveries`(`status`);
CREATE UNIQUE INDEX `idx_knowledge_deliveries_delivery_key` ON `knowledge_deliveries`(`delivery_key`);
CREATE INDEX `idx_knowledge_deliveries_artifact_set_id` ON `knowledge_deliveries`(`artifact_set_id`);
CREATE INDEX `idx_jobs_workflow_id` ON `jobs`(`workflow_id`);
CREATE INDEX `idx_jobs_deleted_at` ON `jobs`(`deleted_at`,`deleted_at`);
CREATE INDEX `idx_jobs_compensated_by_job_id` ON `jobs`(`compensated_by_job_id`);
CREATE INDEX `idx_jobs_compensation_of_job_id` ON `jobs`(`compensation_of_job_id`);
CREATE INDEX `idx_jobs_status` ON `jobs`(`status`);
CREATE INDEX `idx_job_executions_podcast_id` ON `job_executions`(`podcast_id`);
CREATE INDEX `idx_job_executions_job_id` ON `job_executions`(`job_id`);
CREATE INDEX `idx_job_executions_deleted_at` ON `job_executions`(`deleted_at`);
CREATE INDEX `idx_job_feed_attempts_podcast_id` ON `job_feed_attempts`(`podcast_id`);
CREATE INDEX `idx_feed_attempt_job` ON `job_feed_attempts`(`job_id`);
CREATE INDEX `idx_job_feed_attempts_deleted_at` ON `job_feed_attempts`(`deleted_at`);
CREATE INDEX `idx_scheduler_runs_job_id` ON `scheduler_runs`(`job_id`);
CREATE INDEX `idx_scheduler_runs_scheduled_at` ON `scheduler_runs`(`scheduled_at`);
CREATE INDEX `idx_scheduler_runs_status` ON `scheduler_runs`(`status`);
CREATE INDEX `idx_scheduler_runs_workflow_id` ON `scheduler_runs`(`workflow_id`);
CREATE INDEX `idx_reports_deleted_at` ON `reports`(`deleted_at`);
CREATE INDEX `idx_reports_publish_to_homepage` ON `reports`(`publish_to_homepage`);
CREATE UNIQUE INDEX `idx_reports_job_id` ON `reports`(`job_id`);
CREATE INDEX idx_podcasts_subscribed_date ON podcasts(is_subscribed, newest_episode_date);
CREATE INDEX idx_podcasts_recent_update_desc ON podcasts(COALESCE(newest_episode_date, created_at) DESC, id DESC);
CREATE INDEX idx_podcasts_subscribed_added ON podcasts(is_subscribed, added_date);
CREATE INDEX idx_podcasts_added_date_desc ON podcasts(added_date DESC, id DESC);
CREATE INDEX idx_podcasts_episode_count_desc ON podcasts(episode_count DESC, id DESC);
CREATE INDEX idx_podcasts_title_nocase ON podcasts(title COLLATE NOCASE ASC, id ASC);
CREATE INDEX idx_episodes_podcast_date ON episodes(podcast_id, published_date);
CREATE INDEX idx_episodes_podcast_published_id_desc ON episodes(podcast_id, published_date DESC, id DESC);
CREATE INDEX idx_workflows_enabled ON workflows(is_enabled);
CREATE INDEX idx_workflows_updated_at_desc ON workflows(updated_at DESC, id DESC);
CREATE INDEX idx_job_executions_status ON job_executions(status);
CREATE INDEX idx_feed_snapshots_evict ON feed_snapshots (validated_at, retrieved_at);
CREATE UNIQUE INDEX idx_jobs_one_active_per_workflow
ON jobs(workflow_id)
WHERE deleted_at IS NULL AND status IN ('pending', 'running', 'finalizing');
CREATE INDEX idx_feed_user_agent_gates_state
ON feed_user_agent_gates (domain, state, probe_eligible_at);
CREATE INDEX idx_feed_user_agent_gate_audits_key
ON feed_user_agent_gate_audits (domain, user_agent_fingerprint, id);
CREATE INDEX idx_feed_user_agent_gate_recovery_status
ON feed_user_agent_gate_recovery_feeds (domain, user_agent_fingerprint, status);
CREATE INDEX idx_episode_triage_queue_position
		ON episode_triage_decisions(queue_state, queue_position, episode_id)
	;
CREATE UNIQUE INDEX idx_episode_processing_runs_one_active
ON episode_processing_runs(episode_id)
WHERE status IN ('queued', 'running', 'waiting_external');
CREATE UNIQUE INDEX idx_episode_artifact_sets_one_current
ON episode_artifact_sets(episode_id)
WHERE is_current = 1;
CREATE INDEX `idx_episode_audio_assets_episode_id` ON `episode_audio_assets`(`episode_id`);
CREATE INDEX `idx_episode_audio_assets_updated_at` ON `episode_audio_assets`(`updated_at`);
CREATE INDEX `idx_episode_audio_assets_created_at` ON `episode_audio_assets`(`created_at`);
CREATE INDEX `idx_episode_audio_assets_failed_at` ON `episode_audio_assets`(`failed_at`);
CREATE INDEX `idx_episode_audio_assets_ready_at` ON `episode_audio_assets`(`ready_at`);
CREATE INDEX `idx_episode_audio_assets_claim_expires_at` ON `episode_audio_assets`(`claim_expires_at`);
CREATE INDEX `idx_episode_audio_assets_status` ON `episode_audio_assets`(`status`);
CREATE INDEX `idx_episode_audio_assets_source_digest` ON `episode_audio_assets`(`source_digest`);
CREATE UNIQUE INDEX idx_episode_audio_assets_one_active
ON episode_audio_assets(episode_id)
WHERE status IN ('queued', 'downloading');
CREATE UNIQUE INDEX idx_episode_audio_assets_ready_source
ON episode_audio_assets(episode_id, source_digest)
WHERE status = 'ready';
CREATE INDEX `idx_processing_schedule_runs_updated_at` ON `processing_schedule_runs`(`updated_at`);
CREATE INDEX `idx_processing_schedule_runs_created_at` ON `processing_schedule_runs`(`created_at`);
CREATE INDEX `idx_processing_schedule_runs_finished_at` ON `processing_schedule_runs`(`finished_at`);
CREATE INDEX `idx_processing_schedule_runs_status` ON `processing_schedule_runs`(`status`);
CREATE INDEX `idx_processing_schedule_runs_scheduled_for` ON `processing_schedule_runs`(`scheduled_for`);
CREATE INDEX `idx_processing_schedule_items_processing_run_id` ON `processing_schedule_items`(`processing_run_id`);
CREATE INDEX `idx_processing_schedule_items_episode_id` ON `processing_schedule_items`(`episode_id`);
CREATE INDEX `idx_processing_schedule_items_schedule_run_id` ON `processing_schedule_items`(`schedule_run_id`);
CREATE INDEX `idx_processing_schedule_items_updated_at` ON `processing_schedule_items`(`updated_at`);
CREATE INDEX `idx_processing_schedule_items_created_at` ON `processing_schedule_items`(`created_at`);
CREATE UNIQUE INDEX idx_processing_schedule_runs_trigger_key
ON processing_schedule_runs(trigger_key);
CREATE UNIQUE INDEX idx_processing_schedule_items_run_episode
ON processing_schedule_items(schedule_run_id, episode_id);
COMMIT;
